config/routes.rb
Rails.application.routes.draw do
  
  resources :events
get 'static_pages/home'
get  '/help',    to: 'static_pages#help'
get  '/about',   to: 'static_pages#about'
get  '/contact', to: 'static_pages#contact'
get  '/signup',  to: 'users#new'

  
post '/signup', to: 'users#create'
get  '/login',   to: 'sessions#new'
post 'bookings' , to:'bookings#create'
#get '/open_newpage_forbook' ,to: 'userbooking#new'
#get 'new_booking' , to:'bookings#index'
#get 'book_new_room' , to:'userbooking#create'
#get '/bookings', to:'bookings#create'
#get '/bookings_new', to: 'bookings#new'
#post   'room_book' , to: 'bookings#create'


post   '/login',   to: 'sessions#create'
delete '/logout',  to: 'sessions#destroy'

resources :users
resources :account_activations, only: [:edit]
resources :user_bookings
resources :rooms do 
	resources :bookings
end
resources :demos
resources :user_apps
resources :microposts
resources :tests
  

root 'static_pages#home'

end

app/controllers/demos_controller.rb
class DemosController < ApplicationController
  before_action :set_demo, only: [:show, :edit, :update, :destroy]

  # GET /demos
  # GET /demos.json
  def index
    @demos = Demo.all
  end

  # GET /demos/1
  # GET /demos/1.json
  def show
  end

  # GET /demos/new
  def new
    @demo = Demo.new
  end

  # GET /demos/1/edit
  def edit
  end

  # POST /demos
  # POST /demos.json
  def create
    @demo = Demo.new(demo_params)

    respond_to do |format|
      if @demo.save
        format.html { redirect_to @demo, notice: 'Demo was successfully created.' }
        format.json { render :show, status: :created, location: @demo }
      else
        format.html { render :new }
        format.json { render json: @demo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /demos/1
  # PATCH/PUT /demos/1.json
  def update
    respond_to do |format|
      if @demo.update(demo_params)
        format.html { redirect_to @demo, notice: 'Demo was successfully updated.' }
        format.json { render :show, status: :ok, location: @demo }
      else
        format.html { render :edit }
        format.json { render json: @demo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /demos/1
  # DELETE /demos/1.json
  def destroy
    @demo.destroy
    respond_to do |format|
      format.html { redirect_to demos_url, notice: 'Demo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_demo
      @demo = Demo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def demo_params
      params.require(:demo).permit(:name, :email)
    end
end

app/helpers/demos_helper.rb
module DemosHelper
end

app/views/demos/edit.html.erb
<h1>Editing Demo</h1>

<%= render 'form', demo: @demo %>

<%= link_to 'Show', @demo %> |
<%= link_to 'Back', demos_path %>

app/views/demos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Demos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @demos.each do |demo| %>
      <tr>
        <td><%= demo.name %></td>
        <td><%= demo.email %></td>
        <td><%= link_to 'Show', demo %></td>
        <td><%= link_to 'Edit', edit_demo_path(demo) %></td>
        <td><%= link_to 'Destroy', demo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Demo', new_demo_path %>

app/views/demos/new.html.erb
<h1>New Demo</h1>

<%= render 'form', demo: @demo %>

<%= link_to 'Back', demos_path %>

app/views/demos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @demo.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @demo.email %>
</p>

<%= link_to 'Edit', edit_demo_path(@demo) %> |
<%= link_to 'Back', demos_path %>