config/routes.rb
Rails.application.routes.draw do
  
  resources :events
get 'static_pages/home'
get  '/help',    to: 'static_pages#help'
get  '/about',   to: 'static_pages#about'
get  '/contact', to: 'static_pages#contact'
get  '/signup',  to: 'users#new'

  
post '/signup', to: 'users#create'
get  '/login',   to: 'sessions#new'
post 'bookings' , to:'bookings#create'
#get '/open_newpage_forbook' ,to: 'userbooking#new'
#get 'new_booking' , to:'bookings#index'
#get 'book_new_room' , to:'userbooking#create'
#get '/bookings', to:'bookings#create'
#get '/bookings_new', to: 'bookings#new'
#post   'room_book' , to: 'bookings#create'


post   '/login',   to: 'sessions#create'
delete '/logout',  to: 'sessions#destroy'

resources :users
resources :account_activations, only: [:edit]
resources :user_bookings
resources :rooms do 
	resources :bookings
end
resources :demos
resources :user_apps
resources :microposts
resources :tests
  

root 'static_pages#home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
	belongs_to :user
	belongs_to :room

	validate :check_date_uniqueness
	validates_presence_of :start_at
	validates_presence_of :end_at


	def check_date_uniqueness
	    
		if Booking.where("start_at = ? AND end_at = ? AND room_id = ?",start_at,end_at,room_id).exists?
			errors.add("room is not available on this date")
			# return false
		else
			return true
		end
	end
	

	
end

app/models/facility.rb
class Facility < ApplicationRecord
	has_many :room_facilities 
	has_many :rooms, through: :room_facilities
end

app/models/purpose.rb
class Purpose < ApplicationRecord
end

app/models/room.rb
class Room < ApplicationRecord
	has_many :room_facilities 
	has_many :facilities, through: :room_facilities
	
	has_many :bookings
	has_many :users,through: :bookings

end

app/models/room_facility.rb
class RoomFacility < ApplicationRecord
	belongs_to :room
	belongs_to :facility	
end

app/models/user.rb
class User < ApplicationRecord
attr_accessor :remember_token
has_many :bookings
has_many :rooms ,through: :bookings

before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
 has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

def self.new_token
    SecureRandom.urlsafe_base64
  end
def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
 def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

end

app/controllers/demos_controller.rb
class DemosController < ApplicationController
  before_action :set_demo, only: [:show, :edit, :update, :destroy]

  # GET /demos
  # GET /demos.json
  def index
    @demos = Demo.all
  end

  # GET /demos/1
  # GET /demos/1.json
  def show
  end

  # GET /demos/new
  def new
    @demo = Demo.new
  end

  # GET /demos/1/edit
  def edit
  end

  # POST /demos
  # POST /demos.json
  def create
    @demo = Demo.new(demo_params)

    respond_to do |format|
      if @demo.save
        format.html { redirect_to @demo, notice: 'Demo was successfully created.' }
        format.json { render :show, status: :created, location: @demo }
      else
        format.html { render :new }
        format.json { render json: @demo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /demos/1
  # PATCH/PUT /demos/1.json
  def update
    respond_to do |format|
      if @demo.update(demo_params)
        format.html { redirect_to @demo, notice: 'Demo was successfully updated.' }
        format.json { render :show, status: :ok, location: @demo }
      else
        format.html { render :edit }
        format.json { render json: @demo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /demos/1
  # DELETE /demos/1.json
  def destroy
    @demo.destroy
    respond_to do |format|
      format.html { redirect_to demos_url, notice: 'Demo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_demo
      @demo = Demo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def demo_params
      params.require(:demo).permit(:name, :email)
    end
end

app/controllers/example_user.rb
class User
  attr_accessor :name, :email

  def initialize(attributes = {})
    @name  = attributes[:name]
    @email = attributes[:email]
  end

  def formatted_email
    "#{@name} <#{@email}>"
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
	def index
		@rooms = Room.where(is_availiable: true)
	end

	def new
		@newroombook = Room.new
   	end
  
	def show
  	 @allroombookings = Room.all
  end
  
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :set_test, only: [:show, :edit, :update, :destroy]

  # GET /tests
  # GET /tests.json
  def index
    @tests = Test.all
  end

  # GET /tests/1
  # GET /tests/1.json
  def show
  end

  # GET /tests/new
  def new
    @test = Test.new
  end

  # GET /tests/1/edit
  def edit
  end

  # POST /tests
  # POST /tests.json
  def create
    @test = Test.new(test_params)

    respond_to do |format|
      if @test.save
        format.html { redirect_to @test, notice: 'Test was successfully created.' }
        format.json { render :show, status: :created, location: @test }
      else
        format.html { render :new }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tests/1
  # PATCH/PUT /tests/1.json
  def update
    respond_to do |format|
      if @test.update(test_params)
        format.html { redirect_to @test, notice: 'Test was successfully updated.' }
        format.json { render :show, status: :ok, location: @test }
      else
        format.html { render :edit }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tests/1
  # DELETE /tests/1.json
  def destroy
    @test.destroy
    respond_to do |format|
      format.html { redirect_to tests_url, notice: 'Test was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test
      @test = Test.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_params
      params.require(:test).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/demos_helper.rb
module DemosHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

 def current_user
   @current_user ||= User.find_by(id: session[:user_id])

  end
def log_out
      forget(current_user)   
   session.delete(:user_id)
    @current_user = nil

end
def logged_in?
    !current_user.nil?
  end
 
def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/user_apps_helper.rb
module UserAppsHelper
end

app/helpers/users_helper.rb
module UsersHelper
 def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Meeting Room Booking</a>
  </small>
  <nav>
    <ul>
      <!-- <li><%= link_to "About",   about_path %></li> -->
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right boldclass">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        
           <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
             <!-- <li><%= link_to "Settings", '#' %></li> -->
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        
          <li><%= link_to "Log in", login_path,id:"loginUser" %></li>
      
      </ul>
    </nav>
  </div>
</header>
<style>
.navbar-inverse .navbar-nav > li > a  {
    color: #FFFFFF;
}
.boldclass{
  font-weight: bold;
}
</style>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%#= stylesheet_link_tag "application-print", :media => "print" ,'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    

    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      

      <%= yield %>
      <%= render 'layouts/footer' %>

       <%#= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>